server {
    location ~ \.unityweb$ {
        gzip on;
        gzip_types application/octet-stream;
        add_header Content-Encoding gzip;
        add_header Content-Type application/octet-stream;
    }
}